[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "frontend"
]

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
redb = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = "5.3"
utoipa-swagger-ui = { version = "8.1", features = ["axum"] }
tower-http = { version = "0.5", features = ["cors"] }